=== keigen-shu/open2jam/src/resources/skin_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:nonstandard:resources" elementFormDefault="qualified" targetNamespace="urn:nonstandard:resources">
    <xsd:element name="Resources">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="spriteset">
                    <xsd:annotation>
                        <xsd:documentation>
A set of sprites.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element ref="skin" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="skin">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="layer">
                    <xsd:annotation>
                        <xsd:documentation>
Main layers. From back to front.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="name" type="nonEmptyString" use="required">
                <xsd:annotation>
                    <xsd:documentation>
The name of the skin, it will be used in the skin configuration window.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute default="7" name="keys" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
The number of keys.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute default="false" name="scratch" type="xsd:boolean">
                <xsd:annotation>
                    <xsd:documentation>
Use the scratch.
Boolean type {true|false}.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="judgment_line" type="xsd:nonNegativeInteger" use="required">
                <xsd:annotation>
                    <xsd:documentation>
The judgment line position. It has nothing to do with the sprite.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute default="800" name="width" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
Width of the skin.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute default="600" name="height" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
Height of the skin.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="spriteset">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="sprite">
                    <xsd:annotation>
                        <xsd:documentation>
A sprite, can be used in multiples entities.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="sprite">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="frame">
                    <xsd:annotation>
                        <xsd:documentation>
A frame of the sprite.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="spriteIDPattern" use="required">
                <xsd:annotation>
                    <xsd:documentation>
The ID of the sprite. To be used in the entity sprite attribute.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="framespeed" type="xsd:decimal">
                <xsd:annotation>
                    <xsd:documentation>
The duration of the animation.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="alpha" type="xsd:boolean">
                <xsd:annotation>
                    <xsd:documentation>
Will the sprite use alpha something?
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="frame">
        <xsd:complexType>
            <xsd:attribute name="file" type="filePattern" use="required">
                <xsd:annotation>
                    <xsd:documentation>
The graphic file. Only jpg/jpeg or png.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="x" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
The position x in the graphic file.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="y" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
The position y in the graphic file.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="w" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
The width of the sprite in the graphic file.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="h" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
The height of the sprite in the graphic file.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="scale_x" type="xsd:decimal"/>
            <xsd:attribute name="scale_y" type="xsd:decimal"/>
            <xsd:attribute name="scale" type="xsd:decimal"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="layer">
        <xsd:complexType>
            <xsd:choice>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="entity">
                    <xsd:annotation>
                        <xsd:documentation>
An entity. Can use any sprite/s.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="styles">
                    <xsd:annotation>
                        <xsd:documentation>
A set of styles.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:choice>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="styles">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="style">
                    <xsd:annotation>
                        <xsd:documentation>
A style.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="nonEmptyString" use="required">
                <xsd:annotation>
                    <xsd:documentation>
The ID of the styles. It will be shown in the Skin configuration window.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="style">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="entity">
                    <xsd:annotation>
                        <xsd:documentation>
An entity. Can use any sprite/s.
Style one.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="nonEmptyString" use="required">
                <xsd:annotation>
                    <xsd:documentation>
The ID of the style. It will be shown in the Skin configuration window.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="entity">
        <xsd:complexType>
            <xsd:attribute name="id" type="entityID">
                <xsd:annotation>
                    <xsd:documentation>
ID. Optional.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="x" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
Position x in the skin.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="y" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
Position y in the skin.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="z-index" type="xsd:nonNegativeInteger">
                <xsd:annotation>
                    <xsd:documentation>
Position z in the skin.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="animation" type="xsd:NCName">
                <xsd:annotation>
                    <xsd:documentation>
Type of animation.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute> <!-- TODO -->
            <xsd:attribute name="fill_direction" type="fillsValues">
                <xsd:annotation>
                    <xsd:documentation>
Direction of the fill. Only used by  BAR entities.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="sprite" type="entitySprites" use="required">
                <xsd:annotation>
                    <xsd:documentation>
A sprite or a set of sprites. Use ,(comma) to separate them.
Ex:
sprite1, sprite2, ...
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="head" type="entitySprites">
                <xsd:annotation>
                    <xsd:documentation>
Only used in NOTE_x . The head of the longnote sprite. If null the "sprite" attribute sprite will be used.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="body" type="entitySprites">
                <xsd:annotation>
                    <xsd:documentation>
Only used in NOTE_x . The body of the longnote sprite. If null the "sprite" attribute sprite will be used.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="tail" type="entitySprites">
                <xsd:annotation>
                    <xsd:documentation>
Only used in NOTE_x . The tail of the longnote sprite. If null the "sprite" attribute sprite will be used.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="title" type="entitySprites">
                <xsd:annotation>
                    <xsd:documentation>
Only used in JAM_COUNTER and COMBO_COUNTER . The title of the counter. It will be centered over the numbers.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="filePattern">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value=".+\.(([jJ][pP][eE]?[gG])|([pP][nN][gG]))"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="nonEmptyString">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(\w+ *)+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="spriteIDPattern">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(([a-zA-Z_0-9]+){1})" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="entitySprites">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="((([a-zA-Z_]+_[0-9]\s{0,},{1}\s{0,}){9}([a-zA-Z_]+_[0-9]){1}){1})"/>    <!-- counters numbers (10 sprites: name_n) or -->
            <xsd:pattern value="(([a-zA-Z_0-9]+){1})" />                                                <!-- a single sprite -->
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="fillsValues">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="left_to_right"/>
            <xsd:enumeration value="right_to_left"/>
            <xsd:enumeration value="up_to_down"/>
            <xsd:enumeration value="down_to_up"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="entityID">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="NOTE_1"/>
            <xsd:enumeration value="NOTE_2"/>
            <xsd:enumeration value="NOTE_3"/>
            <xsd:enumeration value="NOTE_4"/>
            <xsd:enumeration value="NOTE_5"/>
            <xsd:enumeration value="NOTE_6"/>
            <xsd:enumeration value="NOTE_7"/>
            <xsd:enumeration value="NOTE_SC"/>
            <xsd:enumeration value="MEASURE_MARK"/>
            <xsd:enumeration value="JUDGMENT_LINE"/>
            <xsd:enumeration value="EFFECT_JUDGMENT_PERFECT"/>
            <xsd:enumeration value="EFFECT_JUDGMENT_COOL"/>
            <xsd:enumeration value="EFFECT_JUDGMENT_GOOD"/>
            <xsd:enumeration value="EFFECT_JUDGMENT_BAD"/>
            <xsd:enumeration value="EFFECT_JUDGMENT_MISS"/>
            <xsd:enumeration value="EFFECT_LONGFLARE"/>
            <xsd:enumeration value="EFFECT_CLICK"/>
            <xsd:enumeration value="PRESSED_NOTE_1"/>
            <xsd:enumeration value="PRESSED_NOTE_2"/>
            <xsd:enumeration value="PRESSED_NOTE_3"/>
            <xsd:enumeration value="PRESSED_NOTE_4"/>
            <xsd:enumeration value="PRESSED_NOTE_5"/>
            <xsd:enumeration value="PRESSED_NOTE_6"/>
            <xsd:enumeration value="PRESSED_NOTE_7"/>
            <xsd:enumeration value="PRESSED_NOTE_SC"/>
            <xsd:enumeration value="FPS_COUNTER"/>
            <xsd:enumeration value="COUNTER_JUDGMENT_PERFECT"/>
            <xsd:enumeration value="COUNTER_JUDGMENT_COOL"/>
            <xsd:enumeration value="COUNTER_JUDGMENT_GOOD"/>
            <xsd:enumeration value="COUNTER_JUDGMENT_BAD"/>
            <xsd:enumeration value="COUNTER_JUDGMENT_MISS"/>
            <xsd:enumeration value="MAXCOMBO_COUNTER"/>
            <xsd:enumeration value="SCORE_COUNTER"/>
            <xsd:enumeration value="JAM_COUNTER"/>
            <xsd:enumeration value="COMBO_COUNTER"/>
            <xsd:enumeration value="MINUTE_COUNTER"/>
            <xsd:enumeration value="SECOND_COUNTER"/>
            <xsd:enumeration value="COMBO_TITLE"/>
            <xsd:enumeration value="JAM_TITLE"/>
            <xsd:enumeration value="PILL_1"/>
            <xsd:enumeration value="PILL_2"/>
            <xsd:enumeration value="PILL_3"/>
            <xsd:enumeration value="PILL_4"/>
            <xsd:enumeration value="PILL_5"/>
            <xsd:enumeration value="LIFE_BAR"/>
            <xsd:enumeration value="JAM_BAR"/>
            <xsd:enumeration value="TIME_BAR"/>
	    <xsd:enumeration value="BGA"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== keigen-shu/open2jam/src/resources/resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<Resources  xmlns="urn:nonstandard:resources"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="urn:nonstandard:resources skin_schema.xsd">

    <spriteset>
        <sprite id="note_bg">
            <frame x="0" y="0" w="204" h="600" file="Note_BG.png" />
        </sprite>
        
        <sprite id="bga10">
            <frame x="0" y="0" w="596" h="558" file="Playing_BG10.png" />
        </sprite>
        <sprite id="bga2">
            <frame x="0" y="0" w="600" h="560" file="Playing_BG2.jpg" />
        </sprite>
        
        <sprite id="dashboard">
            <frame x="0" y="0" w="596" h="42" file="Playing_Menu.png" />
        </sprite>

        <sprite id="pill">
            <frame x="0" y="52" w="28" h="28" file="main.png" />
        </sprite>

        <sprite id="lifebar_bg">
            <frame x="77"  y="1"  w="11" h="301" file="main.png" />
        </sprite>
        <sprite id="lifebar" framespeed="33.3" >
            <frame x="88"  y="1"  w="11" h="301" file="main.png" />
            <frame x="99"  y="1"  w="11" h="301" file="main.png" />
            <frame x="110" y="1"  w="11" h="301" file="main.png" />
            <frame x="121" y="1"  w="11" h="301" file="main.png" />
            <frame x="132" y="1"  w="11" h="301" file="main.png" />
            <frame x="143" y="1"  w="11" h="301" file="main.png" />
            <frame x="154" y="1"  w="11" h="301" file="main.png" />
            <frame x="165" y="1"  w="11" h="301" file="main.png" />
            <frame x="176" y="1"  w="11" h="301" file="main.png" />
            <frame x="187" y="1"  w="11" h="301" file="main.png" />
        </sprite>


        <sprite id="timebar">
            <frame x="0"  y="183"  w="226" h="72" file="font1.png" />
        </sprite>


        <sprite id="judgmentarea" framespeed="5">
            <frame x="224" y="1"  w="192" h="64" file="main.png" />
            <frame x="224" y="66" w="192" h="64" file="main.png" />
        </sprite>

        <sprite id="pressed_note_lane_white">
            <frame x="425" y="1" w="28" h="266" file="main.png" />
        </sprite>

        <sprite id="pressed_note_lane_blue">
            <frame x="455" y="1" w="22" h="480" file="main.png" />
        </sprite>

        <sprite id="pressed_note_lane_yellow">
            <frame x="478" y="1" w="32" h="480" file="main.png" />
        </sprite>

        <sprite framespeed="5" id="measure_mark">
            <frame x="225" y="134" w="188" h="3" file="main.png" />
            <frame x="225" y="138" w="188" h="3" file="main.png" />
        </sprite>

       <sprite framespeed="12" id="head_note_white">
            <frame x="225" y="142" w="28" h="7" file="main.png" />
            <frame x="225" y="150" w="28" h="7" file="main.png" />
            <frame x="225" y="158" w="28" h="7" file="main.png" />
        </sprite>
        
        <sprite framespeed="12" id="body_note_white">
            <frame x="225" y="143" w="28" h="5" file="main.png" />
            <frame x="225" y="151" w="28" h="5" file="main.png" />
            <frame x="225" y="159" w="28" h="5" file="main.png" />
        </sprite>
        <sprite framespeed="12" id="head_note_blue">
            <frame x="254" y="142" w="22" h="7" file="main.png" />
            <frame x="254" y="150" w="22" h="7" file="main.png" />
            <frame x="254" y="158" w="22" h="7" file="main.png" />
        </sprite>
        <sprite framespeed="12" id="body_note_blue">
            <frame x="254" y="143" w="22" h="5" file="main.png" />
            <frame x="254" y="151" w="22" h="5" file="main.png" />
            <frame x="254" y="159" w="22" h="5" file="main.png" />
        </sprite>
        <sprite framespeed="12" id="head_note_yellow">
            <frame x="277" y="142" w="32" h="7" file="main.png" />
            <frame x="277" y="150" w="32" h="7" file="main.png" />
            <frame x="277" y="158" w="32" h="7" file="main.png" />
        </sprite>
        <sprite framespeed="12" id="body_note_yellow">
            <frame x="277" y="143" w="32" h="5" file="main.png" />
            <frame x="277" y="151" w="32" h="5" file="main.png" />
            <frame x="277" y="159" w="32" h="5" file="main.png" />
        </sprite>

        <!-- This overlaps hiding notes underneath -->
        
        <sprite id="static_keyboard">
            <frame x="208" y="366" w="204" h="120" file="main.png" />
        </sprite>

        <sprite id="jam_bar">
            <frame x="1" y="391" w="191" h="12" file="main.png" />
        </sprite>

        <sprite id="pressed_note_keyboard_white1">
            <frame x="1" y="315" w="31" h="46" file="main.png" />
        </sprite>
        <sprite id="pressed_note_keyboard_white2">
            <frame x="1" y="362" w="10" h="5" file="main.png" />
        </sprite>

        <sprite id="pressed_note_keyboard_blue">
            <frame x="33" y="315" w="22" h="42" file="main.png" />
        </sprite>

        <sprite id="pressed_note_keyboard_yellow">
            <frame x="87" y="315" w="32" h="46" file="main.png" />
        </sprite>


        <sprite id="effect_click_1" framespeed="60" alpha="true">
            <frame x="0"    y="0"   w="256" h="256" file="note_click5_3.png" />
            <frame x="256"  y="0"   w="256" h="256" file="note_click5_3.png" />
            <frame x="512"  y="0"   w="256" h="256" file="note_click5_3.png" />
            <frame x="768"  y="0"   w="256" h="256" file="note_click5_3.png" />
            <frame x="1024" y="0"   w="256" h="256" file="note_click5_3.png" />
            <frame x="0"    y="256" w="256" h="256" file="note_click5_3.png" />
            <frame x="256"  y="256" w="256" h="256" file="note_click5_3.png" />
            <frame x="512"  y="256" w="256" h="256" file="note_click5_3.png" />
            <frame x="768"  y="256" w="256" h="256" file="note_click5_3.png" />
            <frame x="1024" y="256" w="256" h="256" file="note_click5_3.png" />
            <frame x="0"    y="512" w="256" h="256" file="note_click5_3.png" />
        </sprite>

        <sprite id="longflare" framespeed="33.3" alpha="true">
            <frame x="0"    y="0"   w="128" h="128" file="longflare.png" />
            <frame x="128"  y="0"   w="128" h="128" file="longflare.png" />
            <frame x="256"  y="0"   w="128" h="128" file="longflare.png" />
            <frame x="384"  y="0"   w="128" h="128" file="longflare.png" />
            <frame x="512"  y="0"   w="128" h="128" file="longflare.png" />
            <frame x="0"    y="128" w="128" h="128" file="longflare.png" />
            <frame x="128"  y="128" w="128" h="128" file="longflare.png" />
            <frame x="256"  y="128" w="128" h="128" file="longflare.png" />
            <frame x="384"  y="128" w="128" h="128" file="longflare.png" />
            <frame x="512"  y="128" w="128" h="128" file="longflare.png" />
            <frame x="0"    y="256" w="128" h="128" file="longflare.png" />
            <frame x="128"  y="256" w="128" h="128" file="longflare.png" />
            <frame x="256"  y="256" w="128" h="128" file="longflare.png" />
            <frame x="384"  y="256" w="128" h="128" file="longflare.png" />
        </sprite>


        <sprite id="combo_number_0" alpha="true">
            <frame x="41" y="27" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_1" alpha="true">
            <frame x="169" y="27" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_2" alpha="true">
            <frame x="298" y="27" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_3" alpha="true">
            <frame x="426" y="27" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_4" alpha="true">
            <frame x="553" y="27" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_5" alpha="true">
            <frame x="41" y="155" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_6" alpha="true">
            <frame x="169" y="155" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_7" alpha="true">
            <frame x="298" y="155" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_8" alpha="true">
            <frame x="426" y="155" w="46" h="71" file="numbers_1.png" />
        </sprite>
        <sprite id="combo_number_9" alpha="true">
            <frame x="553" y="155" w="46" h="71" file="numbers_1.png" />
        </sprite>

        <sprite id="combo_title" framespeed="12" alpha="true">
            <frame x="0"   y="0"  w="64" h="64" file="combo_title.png" />
            <frame x="64"  y="0"  w="64" h="64" file="combo_title.png" />
            <frame x="128" y="0"  w="64" h="64" file="combo_title.png" />
            <frame x="0"   y="64" w="64" h="64" file="combo_title.png" />
            <frame x="64"  y="64" w="64" h="64" file="combo_title.png" />
            <frame x="128" y="64" w="64" h="64" file="combo_title.png" />
        </sprite>

        <sprite id="judgment_perfect" alpha="true">
            <frame x="0" y="0" w="128" h="128" file="note_cool_1.png" />
        </sprite>
        <sprite id="judgment_cool" alpha="true">
            <frame x="0" y="0" w="128" h="128" file="note_cool_1.png" />
        </sprite>
        <sprite id="judgment_good" alpha="true">
            <frame x="0" y="0" w="128" h="128" file="note_good_1.png" />
        </sprite>
        <sprite id="judgment_bad" alpha="true">
            <frame x="0" y="0" w="128" h="128" file="note_bad_1.png" />
        </sprite>
        <sprite id="judgment_miss" alpha="true">
            <frame x="0" y="0" w="128" h="128" file="note_miss_1.png" />
        </sprite>

        <!-- Score numbers are from PointNum.ojs, resized and then nicely positioned --> 
        <sprite id="score_number_0">
